# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     CardPlayers.Repo.insert!(%SomeModel{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.
alias CardPlayers.Card
CardPlayers.Repo.insert!(%Card{image_number: 0, title: "Clumsy", left_attribute: "Aim", left_value: 1, right_attribute: "Evade", right_value: 1, quote: "I may not have been paying attention that day..."})
CardPlayers.Repo.insert!(%Card{image_number: 1, title: "Flailing", left_attribute: "Aim", left_value: 2, right_attribute: "Force", right_value: 14, quote: "I fired blind"})
CardPlayers.Repo.insert!(%Card{image_number: 2, title: "", left_attribute: "Aim", left_value: 3, right_attribute: "Defend", right_value: 9, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 3, title: "", left_attribute: "Aim", left_value: 4, right_attribute: "Evade", right_value: 8, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 4, title: "", left_attribute: "Aim", left_value: 5, right_attribute: "Evade", right_value: 7, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 5, title: "", left_attribute: "Aim", left_value: 6, right_attribute: "Defend", right_value: 13, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 6, title: "", left_attribute: "Aim", left_value: 7, right_attribute: "Defend", right_value: 12, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 7, title: "", left_attribute: "Aim", left_value: 8, right_attribute: "Defend", right_value: 5, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 8, title: "", left_attribute: "Aim", left_value: 9, right_attribute: "Force", right_value: 7, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 9, title: "", left_attribute: "Aim", left_value: 10, right_attribute: "Defend", right_value: 4, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 10, title: "", left_attribute: "Aim", left_value: 11, right_attribute: "Defend", right_value: 6, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 11, title: "", left_attribute: "Aim", left_value: 12, right_attribute: "Evade", right_value: 6, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 12, title: "", left_attribute: "Aim", left_value: 13, right_attribute: "Evade", right_value: 2, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 13, title: "", left_attribute: "Aim", left_value: 14, right_attribute: "Defend", right_value: 11, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 14, title: "", left_attribute: "Force", left_value: 1, right_attribute: "Defend", right_value: 2, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 15, title: "", left_attribute: "Force", left_value: 2, right_attribute: "Defend", right_value: 3, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 16, title: "", left_attribute: "Force", left_value: 3, right_attribute: "Defend", right_value: 8, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 17, title: "", left_attribute: "Force", left_value: 4, right_attribute: "Aim", right_value: 6, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 18, title: "", left_attribute: "Force", left_value: 5, right_attribute: "Evade", right_value: 13, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 19, title: "", left_attribute: "Force", left_value: 6, right_attribute: "Aim", right_value: 12, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 20, title: "", left_attribute: "Force", left_value: 7, right_attribute: "Evade", right_value: 10, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 21, title: "", left_attribute: "Force", left_value: 8, right_attribute: "Defend", right_value: 10, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 22, title: "", left_attribute: "Force", left_value: 9, right_attribute: "Evade", right_value: 12, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 23, title: "", left_attribute: "Force", left_value: 10, right_attribute: "Evade", right_value: 9, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 24, title: "", left_attribute: "Force", left_value: 11, right_attribute: "Evade", right_value: 14, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 25, title: "", left_attribute: "Force", left_value: 12, right_attribute: "Aim", right_value: 13, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 26, title: "", left_attribute: "Force", left_value: 13, right_attribute: "Defend", right_value: 7, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 27, title: "", left_attribute: "Force", left_value: 14, right_attribute: "Evade", right_value: 3, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 28, title: "", left_attribute: "Evade", left_value: 1, right_attribute: "Aim", right_value: 1, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 29, title: "", left_attribute: "Evade", left_value: 2, right_attribute: "Force", right_value: 6, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 30, title: "", left_attribute: "Evade", left_value: 3, right_attribute: "Aim", right_value: 10, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 31, title: "", left_attribute: "Evade", left_value: 4, right_attribute: "Force", right_value: 4, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 32, title: "", left_attribute: "Evade", left_value: 5, right_attribute: "Force", right_value: 11, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 33, title: "", left_attribute: "Evade", left_value: 6, right_attribute: "Defend", right_value: 14, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 34, title: "", left_attribute: "Evade", left_value: 7, right_attribute: "Aim", right_value: 7, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 35, title: "", left_attribute: "Evade", left_value: 8, right_attribute: "Aim", right_value: 5, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 36, title: "", left_attribute: "Evade", left_value: 9, right_attribute: "Force", right_value: 10, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 37, title: "", left_attribute: "Evade", left_value: 10, right_attribute: "Aim", right_value: 2, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 38, title: "", left_attribute: "Evade", left_value: 11, right_attribute: "Force", right_value: 12, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 39, title: "", left_attribute: "Evade", left_value: 12, right_attribute: "Force", right_value: 13, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 40, title: "", left_attribute: "Evade", left_value: 13, right_attribute: "Defend", right_value: 1, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 41, title: "", left_attribute: "Evade", left_value: 14, right_attribute: "Aim", right_value: 9, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 42, title: "", left_attribute: "Defend", left_value: 1, right_attribute: "Force", right_value: 8, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 43, title: "", left_attribute: "Defend", left_value: 2, right_attribute: "Force", right_value: 2, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 44, title: "", left_attribute: "Defend", left_value: 3, right_attribute: "Evade", right_value: 5, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 45, title: "", left_attribute: "Defend", left_value: 4, right_attribute: "Aim", right_value: 14, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 46, title: "", left_attribute: "Defend", left_value: 5, right_attribute: "Evade", right_value: 4, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 47, title: "", left_attribute: "Defend", left_value: 6, right_attribute: "Aim", right_value: 3, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 48, title: "", left_attribute: "Defend", left_value: 7, right_attribute: "Aim", right_value: 8, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 49, title: "", left_attribute: "Defend", left_value: 8, right_attribute: "Aim", right_value: 11, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 50, title: "", left_attribute: "Defend", left_value: 9, right_attribute: "Force", right_value: 9, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 51, title: "", left_attribute: "Defend", left_value: 10, right_attribute: "Force", right_value: 3, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 52, title: "", left_attribute: "Defend", left_value: 11, right_attribute: "Evade", right_value: 11, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 53, title: "", left_attribute: "Defend", left_value: 12, right_attribute: "Force", right_value: 5, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 54, title: "", left_attribute: "Defend", left_value: 13, right_attribute: "Force", right_value: 1, quote: ""})
CardPlayers.Repo.insert!(%Card{image_number: 55, title: "", left_attribute: "Defend", left_value: 14, right_attribute: "Aim", right_value: 4, quote: ""})

